### PR TITLE
Update MotionScene.java

### PR DESCRIPTION
**Pull request by ZhuSniffsTheRose**
avoid the condition invalidating the property ` motion:autoTransition="animateToStart".`in `<Transition/>`

### CODE REVIEW

**Comment by ZhuSniffsTheRose** [comment]
> @googlebot I signed it!
@googlebot I signed it!

**Comment by jafu888** [comment]
I need to understand what you are trying to do. 
That line was added about 2 months ago based on another persons complaint. 
The goal is of autoTransition is if 
I have two Transitions a->b and c->b
I can say "auto transition to start" on c->b  and as a->b finishes it will jump to c->b starting on c

I does not do that? 
Could you describe the problem you are trying to fix ?

**Comment by ZhuSniffsTheRose** [comment]
> I need to understand what you are trying to do.
> That line was added about 2 months ago based on another persons complaint.
> The goal is of autoTransition is if
> I have two Transitions a->b and c->b
> I can say "auto transition to start" on c->b and as a->b finishes it will jump to c->b starting on c
> 
> I does not do that?
> Could you describe the problem you are trying to fix ?
there is animation: a ->b when finished if motion:autoTransition="animateToStart", I want to back to start: a.

**Comment by jafu888** [comment]
The problem is that is not what they were meant for. (But I may have a bug) 
It was meant for transition chaining.  so you can have a->b->c->d where each "->" is a transition and it will hop from a ,b,c,d.  but you can have the start end reversed  a->b<-c->d (and get that to go a,b,c,d as well)
But the Transition c->b will run backwards. 

say "*" means auto transition away form that point so "a*->b" transition a to b with auto transition to end.
Typically you can  say a->b and b*->c  so that when you reach reach b it automatically transitions to b*->c and animates to C (or jumps if it is set to jumpTo)

but you can just as simply have a a->b and c->b* and get identical behavior (except keyframes and motion properties are directional in there computation) 

That is how it is supposed to work.  
That code was added to prevent the animation accidently running when you are on a a*->b  (or a->b*) and hit a (or b) 
First
I will check to see if I have another bug in the intended behavior.
I will check with the other issue and see if I can solve there problem. 
But then 
I will probably add  another flag. 

I will post here next week

**Comment by jafu888** [comment]
I will merge this and add support for preventing autoTranstion within a Transition as a transtionFlag

**Pull request merged**
