### PR TITLE
Improvement to CircularFlow

### PR DESCRIPTION
**Pull request by rodrigomartind**
Performance improvements in CircularFlow.

https://user-images.githubusercontent.com/24611045/113516883-232e6780-9553-11eb-839a-4629bb9dc02d.mov

### CODE REVIEW

**Comment by rodrigomartindMeli** [comment]
@googlebot I consent

**Comment by rodrigomartind** [comment]
@jafu888 @camaelon 
After that this PR is merged, I will fix the xml in 
`/home/runner/work/constraintlayout/constraintlayout/projects/MotionLayoutVerification/app/src/main/res/layout/verification_922.xml:253: AAPT: error: '140' is incompatible with attribute circularflow_defaultRadius (attr) dimension.`

`circularflow_defaultRadius` now change to a dimension.

**Review by jafu888 — APPROVED** [review]

**Review by camaelon — APPROVED** [review]

**Comment by camaelon** [comment]
you have to modify the validation file using CircularFlow, as it still references the value as integer instead of Dp, so the check fails.

MotionLayoutVerification/app/src/main/res/layout/verification_922.xml:253

**Comment by rodrigomartindMeli** [comment]
> you have to modify the validation file using CircularFlow, as it still references the value as integer instead of Dp, so the check fails.
> 
> MotionLayoutVerification/app/src/main/res/layout/verification_922.xml:253

Done ✅

**Pull request merged**
